import { Container, Heading } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../components/Header';
import Main from '../components/Main';
import useCurrentUserStore from '../hooks/useCurrentUser';

const Home: NextPage = () => {
  const user = useCurrentUserStore((state) => state.user);

  return (
    <div>
      <Head>
        <title>Events Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Header />
        <Main>
          <Heading as="h2" size="lg">
            Home
          </Heading>
          {user && <p>{user.username}</p>}
        </Main>
      </Container>
    </div>
  );
};

export default Home;
