import {
  Box,
  Button,
  Container,
  FormControl,
  FormErrorMessage,
  FormLabel,
  Heading,
  Input,
  VStack,
} from '@chakra-ui/react';
import { NextPage } from 'next';
import Head from 'next/head';
import React, { useState } from 'react';
import Header from '../../components/Header';
import Main from '../../components/Main';
import { useCurrentUserQuery, useEventsQuery } from '../../generated/graphql';

const EventsPage: NextPage = () => {
  useEventsQuery();
  useCurrentUserQuery();
  return (
    <div>
      <Head>
        <title>Login - Events Calender</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Header />
        <Main>
          <Heading as="h2" size="lg">
            Events
          </Heading>
        </Main>
      </Container>
    </div>
  );
};

export default EventsPage;
