import { Container, Heading } from '@chakra-ui/react';
import { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useEffect } from 'react';
import Header from '../../components/Header';
import Main from '../../components/Main';
import useCurrentUserStore from '../../hooks/useCurrentUser';

const logout = async () => {
  await fetch('/api/logout');
};

const LogoutPage: NextPage = () => {
  const router = useRouter();
  const resetUser = useCurrentUserStore((state) => state.resetUser);

  useEffect(() => {
    resetUser();
    logout().then(() => router.push('/'));
  }, []);

  return (
    <div>
      <Head>
        <title>Logout - Events Calender</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Header />
        <Main>
          <Heading as="h2" size="lg">
            Logout
          </Heading>
        </Main>
      </Container>
    </div>
  );
};

export default LogoutPage;
