import { Container, Heading } from '@chakra-ui/react';
import { NextPage } from 'next';
import Head from 'next/head';
import React, { useEffect } from 'react';
import Header from '../../components/Header';
import Main from '../../components/Main';

const logout = async () => {
  await fetch('/api/logout');
};

const RegisterPage: NextPage = () => {
  useEffect(() => {
    logout();
  }, []);

  return (
    <div>
      <Head>
        <title>Logout - Events Calender</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Header />
        <Main>
          <Heading as="h2" size="lg">
            Logout
          </Heading>
        </Main>
      </Container>
    </div>
  );
};

export default RegisterPage;
